<?php

use Gilbitron\Util\Process;

class ProcessTest extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $dir = __DIR__.'/../../data';

        $this->process = new Process("php -S localhost:9000 -t {$dir}");
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $this->process->stop();
    }

    /**
     * @test
     */
    public function it_runs_process()
    {
        $this->assertTrue($this->process->status());
    }
}